import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "./providers";
import { JsonLd } from "@/components/seo/JsonLd";
import {
  buildOrganizationSchema,
  buildSiteNavigationSchema,
  buildWebSiteSchema,
} from "@/lib/seo";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const viewport: Viewport = {
  // Theme-aware browser chrome tinting. The actual <html data-theme> is set
  // at runtime by the anti-flash script in <head>, but media queries here
  // give the OS a hint so PWA splash + iOS status bar match the preferred
  // theme out of the gate.
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#080808" },
    { media: "(prefers-color-scheme: light)", color: "#fafafa" },
  ],
  colorScheme: "light dark",
};

export const metadata: Metadata = {
  title: {
    default: "Dezignxo — Premium 3D Models, Lottie Animations & SVG Icons",
    template: "%s | Dezignxo",
  },
  // Longer, keyword-rich description targeting the ~155 char SERP
  // snippet ceiling. Front-loads what the marketplace IS (3D models,
  // 3D icons, Lottie animations, SVG icons) so Google's snippet picker
  // has a real sentence to display instead of generic copy.
  description:
    "Dezignxo is a creator-driven marketplace for production-ready 3D models, 3D icons, Lottie animations, and SVG icon packs — every asset royalty-free with commercial license.",
  keywords: [
    "3D models",
    "3D icons",
    "Lottie animations",
    "SVG icons",
    "icon pack",
    "royalty-free 3D assets",
    "Blender models",
    "glTF",
    "game-ready assets",
    "Unity assets",
    "Unreal assets",
    "vector icons",
    "marketplace",
    "Dezignxo",
  ],
  authors: [{ name: "Dezignxo" }],
  creator: "Dezignxo",
  publisher: "Dezignxo",
  category: "Digital Asset Marketplace",
  metadataBase: new URL("https://www.dezignxo.com"),
  // Linked from <head>; the PWA manifest itself is generated by app/manifest.ts.
  manifest: "/manifest.webmanifest",
  // Stops mobile browsers from auto-linking phone numbers, addresses and
  // emails that happen to appear in copy — they aren't real CTAs.
  formatDetection: { telephone: false, address: false, email: false },
  // No OG image. The previous /opengraph-image PNG got pinned in
  // Vercel's edge cache with the old "GameChanger" wordmark and we
  // can't invalidate it from the codebase that owns the deployment
  // serving www.dezignxo.com. Better to ship social previews with
  // no image at all than with the wrong brand image - Twitter falls
  // back to a "summary" card, WhatsApp/Facebook just render the
  // title + description with no thumbnail.
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://www.dezignxo.com",
    title: "Dezignxo — Premium 3D Models, Lottie Animations & SVG Icons",
    description:
      "Production-ready 3D models, 3D icons, Lottie animations, and SVG icon packs. Royalty-free commercial license on every download. Browse, buy, or upload your own.",
    siteName: "Dezignxo",
  },
  twitter: {
    card: "summary",
    title: "Dezignxo — Premium 3D Models, Lottie Animations & SVG Icons",
    description:
      "Production-ready 3D models, 3D icons, Lottie animations, and SVG icon packs. Royalty-free commercial license on every download.",
    creator: "@dezignxo",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
  // Google Search Console ownership proof. Next emits the
  //   <meta name="google-site-verification" content="..." />
  // tag inside <head> automatically — same effect as pasting the
  // tag by hand, but driven by the Metadata API so it stays
  // co-located with the rest of our SEO config.
  verification: {
    google: "pFQoLqlGPJR7sOenhC9z737Zlnig0tGs7qOZCx_F3Wc",
  },
  // Canonical URL avoids www / apex / trailing-slash duplication. Per-
  // page metadata generators override this with their own absolute
  // canonical when relevant (e.g. asset detail).
  alternates: {
    canonical: process.env.NEXTAUTH_URL ?? "http://localhost:3000",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <head>
        {/* R2 preconnect — every asset preview, category hero, and Lottie
            animation on the home page fetches from this R2 public host.
            Without preconnect each image waits for a fresh DNS+TLS
            handshake (~200-400ms first-fetch penalty). preconnect lets
            the browser do that work in parallel with HTML parsing, so
            the first image is ready the instant the layout engine
            asks for it. crossOrigin is required for the early-fetch
            optimisation to apply to CORS-fetched bytes. */}
        <link
          rel="preconnect"
          href="https://pub-471747289587402a92b17615e1089adb.r2.dev"
          crossOrigin="anonymous"
        />
        <link
          rel="dns-prefetch"
          href="https://pub-471747289587402a92b17615e1089adb.r2.dev"
        />
        {/* Google profile avatars — only fetched after sign-in, but the
            preconnect cost is free + saves ~200ms when it matters. */}
        <link rel="dns-prefetch" href="https://lh3.googleusercontent.com" />
        {/* Anti-flash theme bootstrap.
            Runs synchronously BEFORE React hydrates and BEFORE first paint —
            so the user never sees a dark frame flicker through to light (or
            vice versa) on page load. Reads the saved choice from localStorage,
            falls back to the OS preference if nothing's saved. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('dezignxo.theme');if(!t){t=window.matchMedia('(prefers-color-scheme: light)').matches?'light':'dark';}document.documentElement.setAttribute('data-theme',t);}catch(e){document.documentElement.setAttribute('data-theme','dark');}})();`,
          }}
        />
        {/* Site-wide structured data — Organization + WebSite (with a
            SearchAction so Google can render the SERP sitelinks-search
            box for brand queries) + SiteNavigationElement (declares the
            primary nav so Google has explicit signals about which
            internal pages qualify for sitelinks under the brand SERP). */}
        <JsonLd
          schema={[
            buildOrganizationSchema(),
            buildWebSiteSchema(),
            buildSiteNavigationSchema(),
          ]}
        />
      </head>
      <body className="min-h-dvh bg-canvas text-primary antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
